# Generated by Django 5.0.3 on 2024-04-24 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='tokens',
            new_name='entry_tokens',
        ),
    ]
