# Generated by Django 5.0.3 on 2024-05-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_tokens_customuser_entry_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfirmationtoken',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
