# Generated by Django 5.0.3 on 2024-04-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_premium_customuser_premium_monthly_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupcode',
            options={'ordering': ['created'], 'verbose_name': 'Signup Code', 'verbose_name_plural': 'Signup Codes'},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='premium_paid_date',
            new_name='premium_start_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='premium_monthly',
        ),
        migrations.AddField(
            model_name='customuser',
            name='premium_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
