# Generated by Django 5.0.3 on 2024-04-16 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_signupcode_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupcode',
            name='active',
        ),
        migrations.RemoveField(
            model_name='signupcode',
            name='used',
        ),
        migrations.RemoveField(
            model_name='signupcode',
            name='used_by',
        ),
    ]
