# Generated by Django 5.0.3 on 2024-04-11 07:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='author',
            new_name='owner',
        ),
        migrations.RemoveField(
            model_name='entry',
            name='body',
        ),
        migrations.AddField(
            model_name='entry',
            name='messages',
            field=models.ManyToManyField(to='entries.entrymessage'),
        ),
    ]
