# Generated by Django 5.0.3 on 2024-07-26 15:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ('-created_at',), 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.CreateModel(
            name='EntryPrompt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('body', models.TextField(max_length=500)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='entries.entry')),
            ],
            options={
                'verbose_name': 'Entry Prompt',
                'verbose_name_plural': 'Entry Prompts',
            },
        ),
    ]
