# Generated by Django 5.0.3 on 2024-04-11 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entrymessage_rename_author_entry_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrymessage',
            name='system',
            field=models.BooleanField(default=False),
        ),
    ]
