# Generated by Django 5.0.3 on 2024-04-11 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_entrymessage_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrymessage',
            old_name='system',
            new_name='system_reply',
        ),
    ]
