# Generated by Django 5.0.3 on 2024-04-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_rename_system_entrymessage_system_reply'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entrymessage',
            options={'ordering': ['created']},
        ),
        migrations.RemoveField(
            model_name='entry',
            name='messages',
        ),
        migrations.AddField(
            model_name='entrymessage',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entries.entry'),
        ),
    ]
